[phases.setup]
nixPkgs = ["php82", "php82Extensions.pgsql", "php82Extensions.pdo_pgsql", "php82Extensions.mbstring", "php82Extensions.openssl", "php82Extensions.curl", "php82Extensions.tokenizer", "nginx", "php82-fpm"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t /app"
